### PR TITLE
[WIP] Forked cmds

### PR DESCRIPTION
**Pull request by austinfrey**
This is an initial PR to get some feedback. No need to think about merging.

Initial functionality is there to build, deploy, invoke, and remove a function.

Items needing to be completed

- Change `build` to `create` to match other providers
- modify `invoke` and `remove` to use `faas-cli` instead of http requests from node
- make commands more flexible and robust as some values are currently hard-coded
- allow for other language templates, node is currently hard-coded

### CODE REVIEW

**Comment by alexellis** [comment]
Looking forward to trying this out. Do you have a few testing instructions?

**Comment by austinfrey** [comment]
From the driver directory, run your test-plugin.sh script. The invoke step sometimes fails since the function hasn't fully booted yet, so walking through the commands manually might be a better option

**Comment by austinfrey** [comment]
@alexellis i think the latest commit here solves the promise/child process issue. please take a look and let me know what you think. running `./test-plugin.sh` will run through all commands.

**Comment by austinfrey** [comment]
Comment out the `serverless init` command if you already have a local instance running. Commands assume localhost is the gateway. Some of the other cmds have hard coded values. I'll work on making it more flexible. I'd also like to test adding some lifecycle events and multiple hooks in the same cmd to make sure the promise imlementation is correct

**Comment by austinfrey** [comment]
@alexellis commits squished and signed

**Comment by alexellis** [comment]
I'm not sure what the conflict is, but can you try fixing with something like this?

```
$ git fetch origin
$ git rebase origin/master
```

**Comment by austinfrey** [comment]
@alexellis merged back to upstream/master to fix the conflict with the README

**Pull request merged**
