### PR TITLE
Fix issue #15 (add push of Docker image)

### LINKED ISSUE #15: Remote push of images.
## Expected Behaviour
When deploying a serverless function with openfaas, there should be a way to push the image to a remote repository.

## Current Behaviour
Right now, if you try to deploy remotely, the remote openfaas server will fail finding the image, because the plugin won't try to push it.

## Possible Solution
There should be some way to either push automatically, with maybe a toggle in the yaml file, or something similar. It'd be nice if doing `serverless deploy` would do the push automatically that is.

## Steps to Reproduce
If you deploy a remote private repository to a machine, say, 10.12.1.2:5000, then the following yaml file would basically deploy a non-working function:
```
service: openfaas-hello-world

provider:
  name: openfaas
  gateway: http://10.12.1.2:8080

functions:
  remote-hello-world:
    lang: node
    handler: ./remote-hello-world
    image: 10.12.1.2:5000/remote-hello-world:0.1

plugins:
  - serverless-openfaas

package:
  artifact: none
```

The remote server will say the following:
```
$ docker service ps --no-trunc=true remote-hello-world
ID                          NAME                       IMAGE                                   NODE                DESIRED STATE       CURRENT STATE             ERROR                                                    PORTS
qa560p1s0fthlluay6542v5ts   remote-hello-world.1       10.12.1.2:5000/remote-hello-world:0.1   seele               Shutdown            Rejected 10 minutes ago   "No such image: 10.12.1.2:5000/remote-hello-world:0.1"
```

Using the raw `faas-cli` command line, I would normally do a `faas build`, `faas push`, `faas deploy` to properly achieve this. The push step isn't happening or isn't exposed currently.

### PR DESCRIPTION
**Pull request by augustin-taiwan**
## Description

For remote deployment, the developers have to push the Docker image to hub/repository before deployment. Currently the developers need to directly use "faas-cli push" for uploading Docker image to the hub. For consistent user experience, I added a option "--push" to "serverless deploy" to trigger "faas-cli push" before "faas-cli deploy".

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
For my need and fixing open issue https://github.com/openfaas/serverless-openfaas/issues/15

## Which issue(s) this PR fixes 

Fixes #15 

## How Has This Been Tested?

I prepared a CentOS as an OpenFaaS server and my MacBook is the local development environment. The test code is https://github.com/openfaas/serverless-openfaas-nodejs. Test cases include:
- After running "serverless package && serverless deploy"
1. Exec "docker images" in MacBook: found the image
2. View Docker hub: not found the image
3. Exec "docker images" in OpenFaaS server: not found the image
4. Exec "docker service ls" in OpenFaaS server: found the service
5. View function status in OpenFaaS web UI: displayed "not ready"

- After running "serverless package && serverless deploy --push"
1. Exec "docker images" in MacBook: found the image
2. View Docker hub: found the image
3. Exec "docker images" in OpenFaaS server: found the image
4. Exec "docker service ls" in OpenFaaS server: found the service
5. View function status in OpenFaaS web UI: displayed "ready"

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Augustin,

This is the first time I've seen your PR.

I'd like to invite you to Slack to discuss further. 

Alex

**Comment by alexellis** [comment]
In the meantime @ivanayov - if you can verify the PR is working as expected then I'll merge.

Alex

**Comment by ivanayov** [comment]
@alexellis  @augustin-taiwan I tested the change and it works as expected.
If you find the design ok, i.e. using push as a flag, then it's good to go IMO

**Review by alexellis — APPROVED** [review]
LGTM

**Pull request merged**
