### PR TITLE
Fix package.json. Move code into lib/

### PR DESCRIPTION
**Pull request by alexdebrie**
Couple structural changes:

1) In the `package.json`, setting the name to `serverless-faas`. This is what NPM will install it as under `node_modules` and is the package Serverless will look for when it's registered as a plugin.

2) Move plugin code from `faas/` to `lib/`

3) Setting the `main` attribute to `lib/index.js`, which has the plugin constructor code.

1 & 3 are particularly important for working as a plugin. After this, users should be able to use the plugin with `npm install --save openfaas/serverless-faas` and adding `serverless-faas` to their plugins section.

Also, before this is published to NPM and all -- any thoughts about naming `serverless-openfaas` rather than `serverless-faas`? Might be a little clearer. cc @austinfrey @alexellis

### CODE REVIEW

**Comment by alexdebrie** [comment]
Well thank you, Derek. The contributing guide is 404'ing for me -- do I just need to follow the directions in the OpenFaaS contributing guide [here](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#sign-your-work) ?

**Comment by austinfrey** [comment]
@alexdebrie looks like it :) didn't realize Derek was monitoring this repo as well

**Comment by alexdebrie** [comment]
@austinfrey Alright, I signed and re-pushed. Let me know if you'd like any changes 😄

**Comment by austinfrey** [comment]
@alexdebrie these changes look good to me. tested this morning. only thing that needs changed is in the `test-plugin.sh` file to swap `faas` for `lib` when copying the directory when testing.

**Comment by alexellis** [comment]
Let me know when this is good to merge, I've also renamed the repository. The package.json etc will also need edits. Thank you guys. 💯

**Comment by alexellis** [comment]
Approved by @austinfrey - merging.

**Comment by alexdebrie** [comment]
Thanks to both of you! I'll take a look at suggested changes from both and try to get updated today.

**Pull request merged**
